"""Ticket Splitter Agent - Breaks down topics into subtasks using Grok."""
from typing import Optional
from pydantic import BaseModel
from app.core.llm import get_llm_client


class SubtaskOutput(BaseModel):
    """A single subtask generated by the agent."""
    title: str
    description: Optional[str] = None
    priority: int = 3
    labels: list[str] = []
    estimated_hours: Optional[float] = None


class ParentTaskOutput(BaseModel):
    """The parent task representing the main topic."""
    title: str
    description: str
    priority: int = 2


class TicketSplitResult(BaseModel):
    """Result of ticket splitting operation."""
    parent_task: ParentTaskOutput
    subtasks: list[SubtaskOutput]
    reasoning: str


class TicketSplitterAgent:
    """AI agent that splits a topic into actionable subtasks."""
    
    def __init__(self):
        self.name = "TicketSplitterAgent"
        self.llm = get_llm_client()
    
    @property
    def system_prompt(self) -> str:
        return """You are a project management expert that breaks down work into actionable tasks.

Given a topic and context, generate:
1. A parent task summarizing the work
2. 3-7 subtasks that together complete the parent task

Rules:
- Each subtask should be independently completable
- Subtasks should be ordered by dependency (do first → do later)
- Assign priority: 1=critical, 2=high, 3=medium, 4=low, 5=nice-to-have
- Add relevant labels (e.g., "backend", "frontend", "testing", "design")
- Keep titles concise but descriptive (max 60 chars)
- Descriptions should explain WHAT, not HOW

Output format (JSON only, no markdown):
{
  "parent_task": {
    "title": "Main task title",
    "description": "Overall description of the work",
    "priority": 2
  },
  "subtasks": [
    {
      "title": "First subtask",
      "description": "What this subtask accomplishes",
      "priority": 2,
      "labels": ["backend"],
      "estimated_hours": 4
    }
  ],
  "reasoning": "Brief explanation of the breakdown logic"
}"""
    
    async def split_ticket(
        self,
        topic: str,
        context: Optional[str] = None,
        project_context: Optional[dict] = None
    ) -> TicketSplitResult:
        """Split a topic into parent task + subtasks."""
        
        # Build the prompt
        prompt_parts = [f"Topic: {topic}"]
        
        if context:
            prompt_parts.append(f"Context: {context}")
        
        if project_context:
            # Include relevant project info
            if project_context.get("name"):
                prompt_parts.append(f"Project: {project_context['name']}")
            if project_context.get("existing_labels"):
                prompt_parts.append(f"Existing labels in project: {', '.join(project_context['existing_labels'])}")
        
        prompt = "\n".join(prompt_parts)
        prompt += "\n\nGenerate the task breakdown as JSON:"
        
        # Call LLM
        response = await self.llm.structured_output(
            prompt=prompt,
            system_prompt=self.system_prompt,
            temperature=0.4  # Balanced creativity
        )
        
        # Parse JSON response
        import json
        try:
            # Clean response if wrapped in markdown
            clean_response = response.strip()
            if clean_response.startswith("```"):
                clean_response = clean_response.split("```")[1]
                if clean_response.startswith("json"):
                    clean_response = clean_response[4:]
                clean_response = clean_response.strip()
            
            data = json.loads(clean_response)
            
            return TicketSplitResult(
                parent_task=ParentTaskOutput(**data["parent_task"]),
                subtasks=[SubtaskOutput(**st) for st in data["subtasks"]],
                reasoning=data.get("reasoning", "")
            )
        except (json.JSONDecodeError, KeyError) as e:
            # Fallback: create basic structure from topic
            return TicketSplitResult(
                parent_task=ParentTaskOutput(
                    title=topic[:60],
                    description=context or topic,
                    priority=2
                ),
                subtasks=[
                    SubtaskOutput(
                        title=f"Implement {topic[:50]}",
                        priority=2,
                        labels=["todo"]
                    ),
                    SubtaskOutput(
                        title=f"Test {topic[:50]}",
                        priority=3,
                        labels=["testing"]
                    ),
                    SubtaskOutput(
                        title=f"Document {topic[:50]}",
                        priority=4,
                        labels=["docs"]
                    )
                ],
                reasoning=f"Fallback breakdown due to parsing error: {str(e)}"
            )


# Singleton instance
_splitter_instance: Optional[TicketSplitterAgent] = None


def get_ticket_splitter() -> TicketSplitterAgent:
    """Get singleton TicketSplitterAgent instance."""
    global _splitter_instance
    if _splitter_instance is None:
        _splitter_instance = TicketSplitterAgent()
    return _splitter_instance
